name: Deploy Angular app
on:
  push:
    branches:
      - master
    paths-ignore:
      '.github/workflows/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install npm
        run: npm ci
      - name: Test app
        run: npm run test -- --watch=false --browsers=ChromeHeadless
    lint:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Get repo code
          uses: actions/checkout@v3
        - name: Install npm
          run: npm ci
        - name: Lint
          run: npm run lint
    build:
      runs-on: ubuntu-latest
      needs: lint
      steps:
        - name: Get repo code
          uses: actions/checkout@v3
        - name: Install npm
          run: npm ci
        - name: Build app
          run: npm run build
#
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Get repo code
#        uses: actions/checkout@v3
#      - name: Install npm
#        run: npm ci
#      - name: Test app
#        run: npm run test -- --watch=false --browsers=ChromeHeadless
#      - name: Lint
#        run: npm run lint
#      - name: Build app
#        run: npm run build

