name: Build & Deploy
on: workflow_dispatch
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.17.0'

      - name: Build app
        run: |
          npm ci
          npm run build:prod

      - name: Cat Index to 404
        run: cat "./dist/cicd/index.html" >> "./dist/cicd/404.html"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          folder: dist/cicd
          ssh-key: ${{ secrets.ACCESS_KEY }}
          branch: gh-pages
