name: Build & Deploy
on: workflow_dispatch
#permissions:
#  contents: write
#  pages: write
#  id-token: write
#concurrency:
#  group: "pages"
#  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
#    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install npm
        run: npm ci

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Deploy
        run: |
          git config user.name Andrey1821
          git config user.email andreykyk888@gmail.com
          git config --list
          npm run deploy



#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Configure Node
#        uses: actions/setup-node@v1
#        with:
#          node-version: '18.17.0'
#
#      - name: Build app
#        run: |
#          npm ci
#          npm run build:prod
#
#      - name: Deploy
#        uses: JamesIves/github-pages-deploy-action@4.1.5
#        with:
#          folder: dist/cicd
#          ssh-key: ${{ secrets.ACCESS_KEY }}
#          branch: gh-pages



#permissions:
#  contents: read
#  pages: write
#  id-token: write
#concurrency:
#  group: "pages"
#  cancel-in-progress: false
#  deploy:
#    environment:
#      name: github-pages
#      url: ${{steps.deployment.outputs.page_url}}
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Install npm
#        run: npm ci
#      - name: Build app
#        run: npm run build
#      - name: Setup Pages
#        uses: actions/configure-pages@v3
#      - name: Upload Artifact
#        uses: actions/upload-pages-artifact@v2
#        with:
#          path: './dist/cicd'
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v2


#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Install npm
#        run: npm ci
#      - name: Create Release
#        uses: actions/create-release@v1
#        if: ${{ steps.changelog.outputs.skipped == 'false' }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_ACTION }}
#        with:
#          tag_name: ${{ steps.changelog.outputs.tag }}
#          release_name: ${{ steps.changelog.outputs.tag }}
#          body: ${{ steps.changelog.outputs.clean_changelog }}
#
#      - name: Deploy
#        run: |
#          npm run deploy


# "deploy": "ng deploy --name=Andrey1821 --email=andreykyk888@gmail.com  --repo=https://Andrey1821:$secrets.GITHUB_TOKEN@github.com/Andrey1821/cicd.git --base-href=/cicd/ --no-silent"

